apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: backend-build-pipeline
  name: backend-build-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: Jenkinsfile/build
    git:
      ref: master
      uri: https://gitlab.com/ocp-demo/backend_quarkus.git
    # sourceSecret:
    #   name: gogs-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: DEV_PROJECT
          value: dev
        - name: CICD_PROJECT
          value: ci-cd
        - name: BACKEND_URL
          value: https://httpbin.org/status/200
        - name: NEXUS_SVC
          value: http://nexus.ci-cd.svc.cluster.local:8081
        - name: NEXUS_REGISTRY_SVC
          value: nexus-registry.ci-cd.svc.cluster.local:5000
        - name: NEXUS_REGISTRY
          value: nexus-registry-ci-cd.apps.cluster-a987.a987.example.opentlc.com
        - name: SONARQUBE_SVC
          value: http://sonarqube:9000
        - name: NEXUS_SECRET
          value: nexus-credential
        - name: USE_INTERNAL_REGISTRY
          value: "false"
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 1
