apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  labels:
    app.kubernetes.io/component: network-tools
    app.kubernetes.io/instance: network-tools
    app.kubernetes.io/part-of: Tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: network-tools
    spec:
      containers:
      - name: network-tools
        image: quay.io/voravitl/tools:latest
        command: ["sleep", "3000"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
            memory: 250Mi
          limits:
            cpu: "0.2"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          drop: ALL
          readOnlyRootFilesystem: false
      terminationGracePeriodSeconds: 10

