apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  version: v2.0
  meshConfig:
    localityLbSetting:
      enabled: false
    disablePolicyChecks: false
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    openshiftRoute:
      enabled: true
    ingress:
        enabled: true
        ingress: false
        runtime:
          container:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          deployment:
            autoScaling:
              maxReplicas: 2
              minReplicas: 1
              targetCPUUtilizationPercentage: 85
              enabled: true
            pod:
              tolerations:
              - key: node.kubernetes.io/unreachable
                operator: Exists
                effect: NoExecute
                tolerationSeconds: 60
        service:
          type: ClusterIP
    egress:
        enabled: false
  general:
    logging:
      componentLevels:
        default: info
      logAsJSON: false
  policy:
    # istiod:
    #   #failOpen: false
    #   disablePolicyChecks: false
    #   localityLbSetting:
    #     enabled: false
    #   outboundTrafficPolicy:
    #     #mode: ALLOW_ANY
    #     mode: REGISTRY_ONLY
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  runtime:
    components:
      prometheus:                   
        deployment:
          replicas: 1
        podDisruption:
          enabled: false
          minAvailable: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60        
      pilot:
        deployment:
          replicas: 1
        podDisruption:
          enabled: false
          minAvailable: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
    defaults:
      deployment:
        podDisruption:
          enabled: false
          minAvailable: 1
  telemetry:
    type: Istiod
  proxy:
    accessLogging:
      envoyService:
        enabled: false
      file:
        encoding: TEXT
        name: /dev/stdout
