apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  version: v1.1
  istio:
    global:
      outboundTrafficPolicy:
        mode: ALLOW_ANY #  REGISTRY_ONLY
      localityLbSetting:
        enabled: true # Default is true
  policy:
    mixer:
      # policyCheckFailOpen allows traffic in cases when the mixer policy service cannot be reached.
      # Default is false which means the traffic is denied when the client is unable to connect to Mixer. 
      failOpen: false
    type: mixer
  gateways:
    openshiftRoute:
      enabled: false
    ingress:
      enabled: true
      runtime:
        container:
          resources:
            requests:
              cpu: 500m
              memory: 300Mi
            limits:
              cpu: 2
              memory: 1Gi
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 2
            minReplicas: 1
            targetCPUUtilizationPercentage: 85
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
    egress:
      enabled: false
  runtime:
    components:
      galley:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      pilot:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      security:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      sidecarInjectorWebhook:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      prometheus:                   
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      mixer.policy:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
      mixer.telemetry:
        deployment:
          autoScaling:
            enabled: false
          replicas: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
    tracing:
      enabled: true
      jaeger:
        template: all-in-one
        sampling: 10000
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
