apiVersion: maistra.io/v2
# Istio 1.6.5
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  meshConfig:
    localityLbSetting:
      enabled: false
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: false
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    egress:
        enabled: true
        runtime:
          container:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
          service: {}
    ingress:
        enabled: true
        ingress: false
        runtime:
          container:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
        service:
          type: ClusterIP
    openshiftRoute:
      enabled: true
  general:
    logging:
      componentLevels:
        default: info
      logAsJSON: false
  policy:
    mixer:
      enableChecks: true
      failOpen: false
      sessionAffinity: false
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.0
  runtime:
    defaults:
      deployment:
        podDisruption:
          enabled: false
  telemetry:
    type: Istiod
  proxy:
    accessLogging:
      envoyService:
        enabled: false
      file:
        encoding: TEXT
        name: /dev/stdout
