# https://github.com/maistra/istio-operator/blob/maistra-2.0/pkg/apis/maistra/v2/smcp_new.yaml
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  version: v2.0
  security:
    dataPlane:
      mtls: true
      automtls: true
    controlPlane:
      mtls: false
      automtls: false
  gateways:
    openshiftRoute:
      enabled: true
    ingress:
        enabled: true
        ingress: false
        runtime:
          container:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          deployment:
            autoScaling:
              maxReplicas: 4
              minReplicas: 1
              targetCPUUtilizationPercentage: 85
              enabled: true
            podDisruption:
              enabled: false
            pod:
              tolerations:
              - key: node.kubernetes.io/unreachable
                operator: Exists
                effect: NoExecute
                tolerationSeconds: 60
        service:
          type: ClusterIP
    egress:
        enabled: false
  general:
    logging:
      componentLevels:
        default: info
      logAsJSON: false
  policy:
    type: Istiod # or Mixer or Remote, Mixer is default for pre v2.0
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  runtime:
    components:
      prometheus:                   
        deployment:
          replicas: 1
        podDisruption:
          enabled: false
          minAvailable: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
    # defaults:
    #   deployment:
    #     podDisruption:
    #       enabled: false
    #       minAvailable: 1
  telemetry:
    type: Istiod
  proxy:
   networking:
    trafficControl:
      outbound:
        policy: ALLOW_ANY # Change to REGISTRY_ONLY to block by default
    accessLogging:
      #envoyService:
      #  enabled: false # Envoy log at ...
      file:
        encoding: TEXT
        name: /dev/stdout 
  tracing:
    sampling: 10000 # scaled integer, 0-100% in 0.01% increments, i.e. 1=.001%, 100=1%, 10000=100%
    type: Jaeger
